### ISSUE TITLE
DRM Content Play get stopped in between

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#10]
When I play a DRM content in between it get stopped. Seeks goes to 0 sec and click on play button doesnt play it.
Following is the error Log:
```
 A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
09-20 17:35:57.171 331-1017/com.example E/OMXNodeInstance: setConfig(1:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
09-20 17:36:20.455 331-1008/com.example E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.bitmovin.player.a.f.a.open(SourceFile:49)
        at com.bitmovin.player.a.f.e.open(SourceFile:119)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:116)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
09-20 17:39:22.513 331-1249/com.example E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
09-20 17:39:22.560 331-1249/com.example E/OMXNodeInstance: setConfig(1:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
09-20 17:39:43.762 331-1281/com.example E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
09-20 17:39:43.802 331-1281/com.example E/OMXNodeInstance: setConfig(1:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
09-20 17:39:44.521 331-638/com.example E/Surface: getSlotFromBufferLocked: unknown buffer: 0xba31c7e8
09-20 17:39:53.682 331-1266/com.example E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.bitmovin.player.a.f.a.open(SourceFile:49)
        at com.bitmovin.player.a.f.e.open(SourceFile:119)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:116)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
09-20 17:39:55.764 331-638/com.example E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb9cd48c0
```

**Comment by SInCE** [comment]
Hi, thanks for reaching out! 

Please understand that issues in this repository are meant to 

- report problems with the given example as they are available here, or 
- to share an idea for another example that you think could be helpful.

For everything else, e.g. problems when using the Android SDK, your player license, or particular issues playing your own content, **please reach out**using our official support channel, either through our chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com.

As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue. If this isn't the case, please reach out through the channels described above. Thank you very much for your understanding!
