### ISSUE TITLE
On Download of a content App get Crashes

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#13]
@matamegger @LudoMichaud 
When I download  a DRM Content Sometime it crashes following is the log
On Every device supporting API 21 to API 28.
I am using  Bitmovin SDK 2.13

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bitmovin.player.services.d.a.e()' on a null object reference
       at com.bitmovin.player.services.g.a.a(SourceFile:92)
       at com.bitmovin.player.services.g.a.g(SourceFile:134)
       at com.bitmovin.player.services.g.a.a(SourceFile:105)
       at com.bitmovin.player.services.g.b$a.a(SourceFile:104)
       at com.bitmovin.player.services.g.b$a.onPostExecute(SourceFile:47)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by LudoMichaud** [comment]
Hi @ravirajjak 
As it seems, there is not such known issue on our side. 
If you don't mind, please could you open a new ticket at support@bitmovin.com and provide your demo app or at least your stream URL and DRM configuration ? We'll then have a look accordingly.
Thanks in advance

**Comment by SInCE** [comment]
As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue.

If this isn't the case, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. 

In your request please make sure to provide 
- the Android SDK you were using
- the full stacktrace + Exception,
- An example + Content(SourceItem), PlayerConfiguration, and instructions for our team so they can reproduce the issue accordingly in order to investigate it.
- any further details you consider to be helpful to replicate the problem accordingly.

Thank you very much for your understanding!
