### ISSUE TITLE
Offline Content Crashes

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#14]
@matamegger @LudoMichaud 
Following is the another crash while downloading the DRM Content

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:385)
       at java.util.concurrent.CopyOnWriteArrayList.remove(CopyOnWriteArrayList.java:481)
       at com.bitmovin.player.offline.b.g.b(SourceFile:78)
       at com.bitmovin.player.offline.b.b.a(SourceFile:170)
       at com.bitmovin.player.offline.b.a.a(SourceFile:93)
       at com.bitmovin.player.offline.b.b$3.onTaskStateChanged(SourceFile:327)
       at com.google.android.exoplayer2.offline.DownloadManager.notifyListenersTaskStateChange(SourceFile:446)
       at com.google.android.exoplayer2.offline.DownloadManager.onTaskStateChange(SourceFile:431)
       at com.google.android.exoplayer2.offline.DownloadManager.access$1600(SourceFile:53)
       at com.google.android.exoplayer2.offline.DownloadManager$Task.changeStateAndNotify(SourceFile:793)
       at com.google.android.exoplayer2.offline.DownloadManager$Task.changeStateAndNotify(SourceFile:781)
       at com.google.android.exoplayer2.offline.DownloadManager$Task.access$000(SourceFile:612)
       at com.google.android.exoplayer2.offline.DownloadManager$Task$2.run(SourceFile:850)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:280)
       at android.app.ActivityThread.main(ActivityThread.java:6710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by SInCE** [comment]
Hi, thanks for reaching out! As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue.

If this isn't the case, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. 

In your request please make sure to provide 
- the Android SDK you were using
- the full stacktrace + Exception,
- An example + Content(SourceItem), PlayerConfiguration, and instructions for our team so they can reproduce the issue accordingly in order to investigate it.
- any further details you consider to be helpful to replicate the problem accordingly.

Thank you very much for your understanding!
