### ISSUE TITLE
Player Timeout 

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#15]
**Sample:** 
Drm Playback

## Describe the bug
While Playing a DRM Content i get Timeout exception. The video is getting streamed from cloudfront on TV.
What might be the cause
10-12 19:07:51.561 19360-23211/com.sample E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://xxx-cdn.xxx.video/secure/_definst_/smil:secure/xxx-secure/prod/5/14/839dsdsa213k.smil/chunk_cad_ridp0aa0br1152007_cs6200_mpd.m4s
        at com.google.android.exoplayer2.upstream.j.open(SourceFile:203)
        at com.bitmovin.player.a.f.a.open(SourceFile:49)
        at com.bitmovin.player.a.f.e.open(SourceFile:119)
        at com.google.android.exoplayer2.source.a.i.b(SourceFile:116)
        at com.google.android.exoplayer2.upstream.Loader$b.run(SourceFile:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
        at com.google.android.exoplayer2.upstream.j.open(SourceFile:200)
        at com.bitmovin.player.a.f.a.open(SourceFile:49) 
        at com.bitmovin.player.a.f.e.open(SourceFile:119) 
        at com.google.android.exoplayer2.source.a.i.b(SourceFile:116) 
        at com.google.android.exoplayer2.upstream.Loader$b.run(SourceFile:320) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 

## Behavior
**Actual:**
While playing video it gets stopped after playing few seconds

**Expected:**
It should play smoothly

**Comment by SInCE** [comment]
Hi, thanks for reaching out! As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue.

If this isn't the case, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. Thank you very much for your understanding!
