### ISSUE TITLE
[DRM]Some videos are not playing on versions < 7

### ISSUE THREAD

**Issue by wesleywillians** [bitmovin/bitmovin-player-android-samples#16]
Hello guys,

I have a big problem with Android Player using DRM (EZDRM).
On Android 4.4, 5, 5.1 and are not playing some videos. These same videos are working fine on Android 7 and 8.

10-13 14:05:32.660 9081-9231/sonmobile.schoolofnet.com E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 505
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.bitmovin.player.a.g.n.open(SourceFile:37)
        at com.bitmovin.player.a.g.c.open(SourceFile:48)
        at com.bitmovin.player.a.g.i.open(SourceFile:119)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

Please me out.
Wesley

**Comment by SInCE** [comment]
Hi, thanks for reaching out! Please understand that this repository and its issues should only discuss problems with the provided examples, or to share you need for additional example, so our team can consider their creation accordingly. 

For every other request or issue using the Android SDK or any other of our services, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. Thank you very much for your understanding!

As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue.
