### ISSUE TITLE
Download Resume Crashes

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#23]
@dweinber @matamegger @LudoMichaud 
While downloading a single  content.
If I Pause the download it gets Paused
If I Resume the download it gets Resumed
If I Cancel the download I Suspend the download and then delete it.
After Canceling when I Pause or Resume I get this Crashes.

java.lang.ArrayIndexOutOfBoundsException: length=1; index=3
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:385)
        at java.util.concurrent.CopyOnWriteArrayList.remove(CopyOnWriteArrayList.java:481)
        at com.bitmovin.player.offline.b.g.b(SourceFile:78)
        at com.bitmovin.player.offline.b.b.a(SourceFile:170)
        at com.bitmovin.player.offline.b.a.a(SourceFile:93)
        at com.bitmovin.player.offline.b.b$3.onTaskStateChanged(SourceFile:327)
        at com.google.android.exoplayer2.offline.f.notifyListenersTaskStateChange(SourceFile:443)
        at com.google.android.exoplayer2.offline.f.onTaskStateChange(SourceFile:428)
        at com.google.android.exoplayer2.offline.f.access$900(SourceFile:53)
        at com.google.android.exoplayer2.offline.f$b.a(SourceFile:791)
        at com.google.android.exoplayer2.offline.f$b.a(SourceFile:779)
        at com.google.android.exoplayer2.offline.f$b.a(SourceFile:844)
        at com.google.android.exoplayer2.offline.l.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6572)
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by ravirajjak** [comment]
Process: com.sonymobile.sonybp, PID: 1900
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.interrupt()' on a null object reference
        at com.google.android.exoplayer2.offline.DownloadManager$Task.cancelDownload(DownloadManager.java:800)
        at com.google.android.exoplayer2.offline.DownloadManager$Task.cancel(DownloadManager.java:767)
        at com.google.android.exoplayer2.offline.DownloadManager.maybeStartTasks(DownloadManager.java:390)
        at com.google.android.exoplayer2.offline.DownloadManager.handleAction(DownloadManager.java:257)
        at com.google.android.exoplayer2.offline.DownloadManager.handleAction(DownloadManager.java:242)
        at com.bitmovin.player.offline.service.a.a(SourceFile:410)
        at com.bitmovin.player.offline.service.a.a(SourceFile:69)
        at com.bitmovin.player.offline.service.a$1.run(SourceFile:356)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:251)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by ravirajjak** [comment]
@dweinber @LudoMichaud @matamegger  cmon  guyz we are your paid customers :(

**Comment by ravirajjak** [comment]
any update on this?

**Comment by ravirajjak** [comment]
any Update? @dweinber @matamegger @LudoMichaud

**Comment by LudoMichaud** [comment]
Hi @ravirajjak 
Thanks for getting in contact. 
As we are already discussing this topic in a private conversation, let me close this issue for now. Please feel free to follow up in the conversation we already have 
Thanks
