### ISSUE TITLE
Download Crash

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#24]
While downloading the content on finishing the activity getting the crash

java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bitmovin.player.services.d.a.e()' on a null object reference
        at com.bitmovin.player.services.g.a.a(SourceFile:92)
        at com.bitmovin.player.services.g.a.g(SourceFile:134)
        at com.bitmovin.player.services.g.a.a(SourceFile:105)
        at com.bitmovin.player.services.g.b$a.a(SourceFile:104)
        at com.bitmovin.player.services.g.b$a.onPostExecute(SourceFile:47)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6572)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by matamegger** [comment]
@ravirajjak 
Can you please provide us in which SDK version you have seen this Exception?
Also can you please explain in detail what you mean with "finishing the activity"?
Thank you!

**Comment by SInCE** [comment]
As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue.

If this isn't the case, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. 

In your request please make sure to provide 
- the Android SDK you were using
- the full stacktrace + Exception,
- An example + Content(SourceItem), PlayerConfiguration, and instructions for our team so they can reproduce the issue accordingly in order to investigate it.
- any further details you consider to be helpful to replicate the problem accordingly.

Thank you very much for your understanding!
