### ISSUE TITLE
TvSample App Crashes

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#28]
@matamegger @dweinber 
app crashes when I launch tv app sample.
following is the log bitmovin sdk version 2.17.1

    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bitmovin.player.services.d.a.e()' on a null object reference
        at com.bitmovin.player.services.g.a.a(SourceFile:92)
        at com.bitmovin.player.services.g.a.g(SourceFile:134)
        at com.bitmovin.player.services.g.a.a(SourceFile:105)
        at com.bitmovin.player.services.g.b$a.a(SourceFile:104)
        at com.bitmovin.player.services.g.b$a.onPostExecute(SourceFile:47)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by SInCE** [comment]
Hi,

did you launch our [BasicPlaybackTV](https://github.com/bitmovin/bitmovin-player-android-samples/blob/master/BasicPlaybackTV/src/main/java/com/bitmovin/samples/tv/playback/basic/MainActivity.java) example as is, or did you modify it?

If so, please try running the example as provided in this repository again. If the problem still persists please share the TV model and version, as well as the AndroidTV version you were using, via email in our official support channel at support@bitmovin.com. Thank you very much in advance!

**Comment by jarhoax** [comment]
Closing due to no activity.
