### ISSUE TITLE
Nullpointer exception in BasicAds example

### ISSUE THREAD

**Issue by Narsuf** [bitmovin/bitmovin-player-android-samples#4]
I get this error after downloading the application and trying to run the BasicAds demo.

``06-19 09:57:35.366 8703-8703/com.bitmovin.player.samples.ads.basic E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bitmovin.player.samples.ads.basic, PID: 8703
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.bitmovin.player.services.f.c.emitPersistent(java.lang.Class, com.bitmovin.player.api.event.data.BitmovinPlayerEvent)' on a null object reference
        at com.bitmovin.player.services.e.a.b(SourceFile:53)
        at com.bitmovin.player.services.e.a.c(SourceFile:47)
        at com.bitmovin.player.services.h.a$2.a(SourceFile:122)
        at com.bitmovin.player.services.h.b$a.a(SourceFile:132)
        at com.bitmovin.player.services.h.b$a.onPostExecute(SourceFile:54)
        at android.os.AsyncTask.finish(AsyncTask.java:667)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)``

**Comment by hawk23** [comment]
Thank you for reporting. This exception happens because you didn't provide a player license key in the `AndroidManifest.xml` file of the `BasicAds` sample app. Please follow the instruction in the `README.md` of this repository to obtain a valid player license key. Once you've put this key in the `AndroidManifest.xml`, the sample application should work without errors.

**Comment by Narsuf** [comment]
Now it works. Thank you.
