### ISSUE TITLE
Crashed on Android TV

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#6]
Hi, While playing DRM Content the app is getting crashed.
Crash Logs
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.ui.PlaybackActivity}: com.bitmovin.player.b
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     **Caused by: com.bitmovin.player.b**
        at com.bitmovin.player.g.f(SourceFile:351)
        at com.bitmovin.player.g.setup(SourceFile:554)
        at com.bitmovin.player.g.<init>(SourceFile:162)
        at com.bitmovin.player.BitmovinPlayer.<init>(SourceFile:102)
        at com.bitmovin.player.BitmovinPlayer.<init>(SourceFile:81)
        at com.bitmovin.player.BitmovinPlayer.<init>(SourceFile:70)
        at com.bitmovin.player.BitmovinPlayerView.a(SourceFile:163)
        at com.bitmovin.player.BitmovinPlayerView.<init>(SourceFile:104)
        at com.example.ui.PlayerUI.<init>(PlayerUI.java:348)
        at com.example.ui.PlaybackActivity.onCreate(PlaybackActivity.java:119)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by jarhoax** [comment]
Can you provide us a few more details please:

- Which SDK Version are you using and which device?
- Does this error occur with every DRM stream or just with few specific ones?
- Can you provide us a sample DRM stream you're using?

Thanks.

**Comment by ravirajjak** [comment]
1. Which SDK Version are you using and which device?
Ans: 2.13 Android SDK

2. Does this error occur with every DRM stream or just with few specific ones?
Ans: Yes

3. Can you provide us a sample DRM stream you're using?
Ans: Using your Sample MPD on Github SampleDrmPlayback Project

**Comment by ravirajjak** [comment]
this.bitmovinPlayerView = new BitmovinPlayerView(context, playerConfiguration);
I request you to give a method to set configuration rather than sending it in parameter.
My thought process I ll bind with XML BitmovinPlayerView and give configuration rather than sending it in parameter and initializing at run time.

**Comment by ravirajjak** [comment]
any update on this its been 10days!!!

**Comment by LudoMichaud** [comment]
Hi, 
Thanks for getting back to us. 
In addition, please could you let me know which device (brand and model) you are using ? 
I'll check this into more details. 
In addition, in case you have a demo stream + DRM configuration that you could share, that would be helpful. Further, please feel free to continue the conversation via email with support@bitmovin.com as it might be more convenient for sharing everything. 
Thanks in advance.

**Comment by SInCE** [comment]
Hi, thanks for reaching out! 

As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue.

If this isn't the case, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. Thank you very much for your understanding!
