### ISSUE TITLE
Offline Content Play Issue

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#7]
Hi,
Following is the crash log. while playing offline content in Android SDK
Version 2.13 BitmovinSDK
SonyXperia G8141
java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:110)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.getLicenseDurationRemainingSec(OfflineLicenseHelper.java:226)
        at com.bitmovin.player.offline.e.a(SourceFile:84)
        at com.bitmovin.player.offline.a.a(SourceFile:202)
        at com.bitmovin.player.offline.a.a(SourceFile:242)
        at com.bitmovin.player.offline.a.h(SourceFile:217)
        at com.bitmovin.player.offline.OfflineContentManager.getOfflineSourceItem(SourceFile:127)
        at in.publicam.sonybp.mobile.activity.ContentActivity.playSource(ContentActivity.java:151)
        at com.example.activity.ContentActivity.lambda$setDefaultInitilization$0$ContentActivity(ContentActivity.java:104)
        at com.example.activity.ContentActivity$$Lambda$0.onClick(Unknown Source:21)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6572)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by matamegger** [comment]
@ravirajjak Thank you for reporting! Our team has identified a potential bug.
We would like to get some further information:
- With what stream happened the crash?
- What are the steps to reproduce the crash?

**Comment by ravirajjak** [comment]
It was a DRM Content.
In your Offline Example you guys are having multiple list. In my case I am having only one list in a Activity.
for example ContentListActivity shows list of Item which just display but I dont give them download option , When a user clicks on a particular Content. I redirect them to ContentDetailActivity where I show them a download option. Once user clicks on Download The code executed according to your sample.
So for suppose in your sample there are ArrayList<ListItems> listitems you guyz add it all the content in it but in my case I add only one content.
When user clicks on download I show them options with check box and download get started on click of AlertDialog Ok Button.
When the download is finished in ContentDetailActivity. User click on a Image to Play the video but Unfortunate it get stopped with the given exception.
for immediate reply contact
https://www.linkedin.com/in/ravi-rajjak-8bb078a4/

**Comment by LudoMichaud** [comment]
hi @ravirajjak 
Have you also checked that your DRM solution allows offline playback ? This is a prerequisite as well.
Please feel free to share your stream / app with support@bitmovin.com, so we can have a look and provide you with targeted information / solutions.
I'm looking forward to your feedback.

**Comment by LudoMichaud** [comment]
@ravirajjak
We will close this issue for now. Please fell free to get in contact with support@bitmovin.com in case you need anything. Our support team will then be happy to help.
